#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/opt/rsh')
import argparse
from fabric import ThreadingGroup

result = ThreadingGroup('stage1-any-sync-node1', 'stage1-any-sync-node2').run('hostname')
print(sorted(result.items()))
