#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/opt/rsh')
from fabric import ThreadingGroup
from rsh import exec_functions

if __name__ == "__main__":
    hosts_or_groups, command = exec_functions.parse_arguments()
    inventory = exec_functions.load_inventory()
    hosts = exec_functions.resolve_hosts(hosts_or_groups, inventory)
    exec_functions.run_command(ThreadingGroup, hosts, command)
