#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
sys.path.append('/opt/rsh')
import argparse
from fabric import SerialGroup

# parse args {{
parser = argparse.ArgumentParser()
parser.add_argument(
    'hostsOrGroups',
    help = 'hosts or groups for execute, comma separated string',
)
group = parser.add_mutually_exclusive_group()
group.add_argument(
    '-i',
    '--forceUseInventory',
    action='store_true',
    help = "force use inventory",
)
group.add_argument(
    '-I',
    '--forceDontUseInventory',
    action='store_true',
    help = "force don't use inventory",
)
args = parser.parse_args()
# }}

#result = SerialGroup('stage1-any-sync-node1', 'stage1-any-sync-node2').run('hostname')
#print(sorted(result.items()))
