on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: release
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - noarch
        os:
          - linux
        include:
          - arch: noarch
            rpm_arch: noarch
            deb_arch: all
    steps:
      - uses: actions/checkout@v4

      - name: make build
        run: make build

      - name: get release version
        id: release-version
        run: |
          echo "$GITHUB_REF_NAME" | sed 's|^[a-zA-Z]\+|RELEASE_VERSION=|' >> $GITHUB_OUTPUT

      # create assets
      - name: create package deb
        uses: bpicode/github-action-fpm@master
        with:
          fpm_opts:
            --name ${{ github.event.repository.name }}
            --version ${{ steps.release-version.outputs.RELEASE_VERSION }}
            --architecture ${{ matrix.deb_arch }}
            --exclude '*/.gitignore'
            --exclude '*/.git'
            --input-type dir
            --output-type deb
            --chdir ./build
          fpm_args: ./
      - name: create package rpm
        uses: bpicode/github-action-fpm@master
        with:
          fpm_opts:
            --name ${{ github.event.repository.name }}
            --version ${{ steps.release-version.outputs.RELEASE_VERSION }}
            --architecture ${{ matrix.rpm_arch }}
            --exclude '*/.gitignore'
            --exclude '*/.git'
            --input-type dir
            --output-type rpm
            --chdir ./build
          fpm_args: ./

      - name: debug
        run: |
          ls -al ./

      - name: Create release deb
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: '*.deb'

      - name: sleep between deb and rpm
        run: sleep 3

      - name: Create release rpm
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: '*.rpm'
